---

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  browser: true
  es6: true


# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'

plugins:
  - babel
